### ISSUE TITLE
Cannot use custom caption and align config variables

### ISSUE THREAD

**Issue by eddively** [todvora/gitbook-plugin-image-captions#13]
`{
    "plugins": [
        "youtubex",
        "search",
        "sectionx",
        "-sharing",
        "image-captions"
    ],
    "pluginsConfig": {
      "image-captions": {
       "caption": "Image Description - _CAPTION_"
      }
    }
}
`

This works.

`{
    "plugins": [
        "youtubex",
        "search",
        "sectionx",
        "-sharing",
        "image-captions"
    ],
    "pluginsConfig": {
      "image-captions": {
       "align": "left"
      }
    }
}
`
This works.

But,
`{
    "plugins": [
        "youtubex",
        "search",
        "sectionx",
        "-sharing",
        "image-captions"
    ],
    "pluginsConfig": {
      "image-captions": {
      "caption": "Image Description - _CAPTION_"
       "align": "left"
      }
    }
}
`
Fails. Am I missing something?

**Comment by todvora** [comment]
Hi,
I just added [a test](https://github.com/todvora/gitbook-plugin-image-captions/commit/6283070d187e77e52a15ab0d29812f3f108e8a91) to verify correct handling of both `caption` and `align` attribute together and everything seems OK.

The problem is probably in the invalid JSON configuration (cannot be parsed). When I take exactly the failing config and let it validate (for example [here](http://jsonlint.com/)):

```
Error: Parse error on line 5:
...ion - _CAPTION_"         "align": "left"     }
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'STRING'
```

There is missing a comma after the `"Image Description - _CAPTION_"` string, which should separate both attributes.

Let me know please, if this resolves your issue.

Best regards,
Tomas

**Comment by eddively** [comment]
Yep, it was the comma.

Thanks.
